tap "jundot/omlx", "https://github.com/jundot/omlx"

brew "stow"
brew "ripgrep"
brew "fd"
brew "gh"
brew "ffmpeg"
brew "pnpm"
brew "go"
brew "xcodes"
brew "aria2"
brew "codex-acp"
brew "omlx"

cask "ghostty"
cask "zed"
cask "1password"
cask "brave-browser"
cask "claude-code@latest"
cask "codex"
cask "android-studio"
cask "discord"
cask "steam"
cask "whatsapp"
cask "signal"
cask "telegram"
