brew "stow"
brew "ripgrep"
brew "fd"
brew "gh"
brew "ffmpeg"
brew "mise"
brew "xcodes"
brew "aria2"

cask "font-jetbrains-mono"
cask "ghostty"
cask "1password"
cask "brave-browser"
cask "claude-code@latest"
cask "codex"
cask "android-studio"
