gui:
  theme:
    activeBorderColor:
      - '#cba6f7'
      - bold
    inactiveBorderColor:
      - '#6c7086'
    selectedLineBgColor:
      - '#313244'
  showFileTree: true
  showRandomTip: false
  showCommandLog: false
  nerdFontsVersion: "3"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: false
  parseEmoji: true
keybinding:
  universal:
    quit: q
    return: <esc>
